image:
  registry: gethue/hue
  tag: 4.10.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  annotations: {}
    # cloud.google.com/load-balancer-type: "Internal"
  loadBalancerIP: null

ingress:
  enabled: false
  # ingressClassName: nginx
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    ## Extend timeout to allow long running queries.
    # nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    # nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    # nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  path: /
  pathType: ImplementationSpecific
  hosts:
    - hue.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

## Use the PostgreSQL chart dependency.
postgresql:
  enabled: true
  global:
    postgresql:
      ## Set to false if bringing your own PostgreSQL.
      ## Authentication parameters
      auth:
        ## The name of an existing secret that contains the postgres password.
        postgresPassword: postgres
        ## PostgreSQL name for a custom user to create
        username: hue
        ## PostgreSQL password for the custom user to create. Ignored if `auth.existingSecret` with key `password` is provided
        password: hue
        ## PostgreSQL name for a custom database to create
        database: hue

hue:
  replicas: 1
  connections:
    # You need to change below configuration incase bringing own PostgresSQL instance and also set postgresql.enabled:false
    db_host: '{{ template "hue.fullname" . }}-postgresql'
    db_port: "5432"
    db_user: hue
    db_pass: hue
    db_name: hue
    db_pass_script: ~
#  interpreters: |-
#    [[[postgresql]]]
#    name = postgresql
#    interface=sqlalchemy
#    options='{"url": "postgresql://hue:hue@my-hue-postgres:5432/hue"}'
  zz_hue_ini: |
    [desktop]
    secret_key=hue123
    app_blacklist=filebrowser,search,hbase,security,jobbrowser,oozie
    django_debug_mode=false
    gunicorn_work_class=sync
    enable_prometheus=true

    [[task_server]]
    enabled=false
    broker_url=redis://redis:6379/0
    result_cache='{"BACKEND": "django_redis.cache.RedisCache", "LOCATION": "redis://redis:6379/0", "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},"KEY_PREFIX": "queries"}'
    celery_result_backend=redis://redis:6379/0

conf:
  hiveSite: {}
    # hive.support.concurrency: false
aws:
  accessKeyId: ""
  secretAccessKey: ""
  awsRegion: "us-east-1"