apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openldap.fullname" . }}-env
  labels:
    app.kubernetes.io/component: openldap
    {{- include "openldap.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}