{{- if .Values.customLdifFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openldap.fullname" . }}-customldif
  labels:
    app.kubernetes.io/component: openldap
    {{- include "openldap.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.customLdifFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}
