apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    app.kubernetes.io/component: openldap
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 389
      targetPort: 389
      protocol: TCP
      name: ldap-port
    - port: 636
      targetPort: 636
      protocol: TCP
      name: ssl-ldap-port
  selector:
    app.kubernetes.io/component: openldap
    {{- include "openldap.selectorLabels" . | nindent 4 }}
