{{- if .Values.phpldapadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}-phpldapadmin
  labels:
    app.kubernetes.io/component: phpldapadmin
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: phpldapadmin
    {{- include "openldap.selectorLabels" . | nindent 4 }}
{{- end }}