apiVersion: v2
appVersion: 3.3.5
description: The Apache Hadoop software library is a framework that allows for the
  distributed processing of large data sets across clusters of computers using simple
  programming models.
home: https://hadoop.apache.org/
icon: http://hadoop.apache.org/images/hadoop-logo.jpg
maintainers:
- email: itzhang89@163.com
  name: itzhang89
name: hadoop
sources:
  - https://github.com/apache/hadoop
  - https://github.com/itzhang89/bigdata-platfrom-charts
version: 1.0.2
