# A headless service to create DNS records
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-hiveserver
  labels:
    app.kubernetes.io/component: hive
    {{- include "hive.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: thrift
    port: 10000
    protocol: TCP
  - name: ui
    port: 10002
    protocol: TCP
  selector:
    app.kubernetes.io/component: hive
    {{- include "hive.selectorLabels" . | nindent 4 }}
