apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hue.fullname" . }}-config
data:
  z-hue-ini: |
    [desktop]

    [[database]]
    engine=postgresql_psycopg2
    host={{ tpl .Values.hue.connections.db_host . }}
    port={{ .Values.hue.connections.db_port }}
    user={{ .Values.hue.connections.db_user }}
{{- if .Values.hue.connections.db_pass_script }}
    password_script={{ .Values.hue.connections.db_pass_script }}
{{- else }}
    password={{ .Values.hue.connections.db_pass }}
{{- end }}
    name={{ .Values.hue.connections.db_user }}

    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id={{ .Values.aws.accessKeyId }}
    secret_access_key={{ .Values.aws.secretAccessKey }}
    region={{ .Values.aws.region }}

    [notebook]
    [[interpreters]]
    {{- if .Values.hue.interpreters }}
    {{ .Values.hue.interpreters | indent 4 }}
    {{- end }}
