{{- if .Values.ingress.httpfs.enabled -}}
{{- $fullname := include "hadoop.fullname" . -}}
{{- $ingressPath := .Values.ingress.httpfs.path -}}
{{- $ingressPort := .Values.httpfs.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}-httpfs
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: httpfs
    {{- include "hadoop.labels" . | nindent 4 }}
{{- if .Values.ingress.httpfs.labels }}
{{ toYaml .Values.ingress.httpfs.labels | indent 4 }}
{{- end }}
{{- with .Values.ingress.httpfs.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.httpfs.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullname }}-httpfs
                port:
                  number: {{ $ingressPort }}
  {{- end }}
{{- end }}