name: build-hadoop-image

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    paths:
      - images/hadoop/base/Dockerfile
      - images/hadoop/Dockerfile
      - images/hadoop/entrypoint.sh
      - images/hadoop/README.md
  workflow_dispatch:
    inputs:
      hadoop_version:
        description: 'hadoop version'
        required: true
        default: 3.3.5

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/hadoop
  HADOOP_VERSION: ${{ github.event.inputs.hadoop_version || '3.3.5' }}

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Workaround: https://github.com/tj-actions/changed-files
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            images/hadoop/base/Dockerfile
            images/hadoop/Dockerfile
            images/hadoop/entrypoint.sh
            images/hadoop/README.md

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Workaround: https://github.com/docker/setup-buildx-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Hadoop Base Docker image
        if: ${{ github.event_name == 'workflow_dispatch' || contains(steps.changed-files.outputs.all_changed_files, 'images/hadoop/base') }}
        id: hadoop-base-build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./images/hadoop/base
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            HADOOP_VERSION=${{ env.HADOOP_VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.HADOOP_VERSION }}-base
          platforms: linux/amd64,linux/arm64
          labels: |
            HADOOP_VERSION=${{ env.HADOOP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Hadoop Docker image
        if: ${{ github.event_name == 'workflow_dispatch' || contains(steps.changed-files.outputs.all_changed_files, 'images/hadoop/Dockerfile') || contains(steps.changed-files.outputs.all_changed_files, 'images/hadoop/entrypoint.sh') }}
        id: hadoop-build-and-push
        uses: docker/build-push-action@v3
        with:
          context: ./images/hadoop
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            HADOOP_BASE_IMAGE=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.HADOOP_VERSION }}-base
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.HADOOP_VERSION }}
          platforms: linux/amd64,linux/arm64
          labels: |
            HADOOP_VERSION=${{ env.HADOOP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Workaround: https://github.com/marketplace/actions/docker-hub-description
      - name: Update Docker Hub Description
        if: contains(steps.changed-files.outputs.all_changed_files, 'images/hadoop/README.md')
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          readme-filepath: images/hadoop/README.md