name: '[Support] Update README metadata'

on:
  pull_request_target:
    branches:
      - main
    paths:
      - charts/**/values.yaml
      - charts/**/Chart.yaml
      - values.yaml.template
      - README.md.gotmpl
    types:
      - closed

env:
  HELM_DOCS_VERSION: "1.11.0"
jobs:
  update-readme-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: install helm-docs
        run: |
          cd /tmp
          wget https://github.com/norwoodj/helm-docs/releases/download/v${{env.HELM_DOCS_VERSION}}/helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          tar -xvf helm-docs_${{env.HELM_DOCS_VERSION}}_Linux_x86_64.tar.gz
          sudo mv helm-docs /usr/local/sbin

      - name: Checkout itzhang89/bigdata-platfrom-charts
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Verify Changed Dockerfile
        id: changed-files
        uses: tj-actions/changed-files@v23.1
        with:
          files: |
            charts/**/values.yaml
            values.yaml.template
            README.md.gotmpl

      - name: Exec the helm-docs
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          changed_files=${{ steps.changed-files.outputs.all_changed_files }}
          charts_dirs_changed="$(echo $changed_files | grep -o "charts/[^/]*/values.yaml" | xargs dirname | sort | uniq || true)"
          for chart in ${charts_dirs_changed}; do
            echo "Updating README.md for ${chart}"
            cp -f ./README.md.gotmpl ${chart}
            helm-docs -c "${chart}"
            rm ${chart}/README.md.gotmpl
          done
      - name: Push changes
        run: |
          # Push all the changes
          cd charts
          if git status -s | grep README.md; then
            git config user.name "$GITHUB_ACTOR"
            git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
            git add --update && git commit -am "Update README.md with helm-dosc" --signoff && git push
          fi
